### ISSUE TITLE
Bitte geänderte Abhängigkeiten klären, danke!

### ISSUE THREAD

**Issue by rin67630** [FrankBau/dl161s#1]
Beim Versuch die Einabaueanweisungen Auf einen aktuellen Raspberry zu folgen kam folgende Meldung:

> sudo apt-get install libusb-dev
> Paketlisten werden gelesen... Fertig
> Abhängigkeitsbaum wird aufgebaut.       
> Statusinformationen werden eingelesen.... Fertig
> Paket libusb-dev ist nicht verfügbar, wird aber von einem anderen Paket
> referenziert. Das kann heißen, dass das Paket fehlt, dass es abgelöst
> wurde oder nur aus einer anderen Quelle verfügbar ist.
> Doch die folgenden Pakete ersetzen es:
> libusb-0.1-4
> E: Für Paket »libusb-dev« existiert kein Installationskandidat.
> 
Ich habe darufhin die libusb-0.1-4 installiert, jedoch schlug das kompilieren fehl:
~/dl161s/dl161s/src $ gcc -o dl161s dl161s.c -lusb
dl161s.c:11:17: fatal error: usb.h: Datei oder Verzeichnis nicht gefunden
 #include <usb.h>
 
Was soll man heute machen?
Danke

**Comment by FrankBau** [comment]
Mit einem aktuellen (2018-04-18) Raspbian Stretch geht es out-of-the-box:
```
sudo apt-get install libusb-dev
git clone https://github.com/FrankBau/dl161s.git
cd dl161s/dl161s/src
gcc -o dl161s dl161s.c -lusb
```

**Comment by rin67630** [comment]
Es tut mir Leid, mein Raspbian upgrade auf Stretch muss schief gegangen sein.
Eine komplette Reinstallation von Raspbian Stretch  löste das Problem.
Verzeihung und danke für die Antwort.
